import { getVersion } from '@tauri-apps/api/app';
import { platform, version as osVersion, arch } from '@tauri-apps/plugin-os';
import { invoke } from '@tauri-apps/api/core';

export interface CrashReportData {
  errorMessage: string;
  errorStack?: string;
  componentStack?: string;
  appVersion: string;
  platform: string;
  osVersion: string;
  architecture: string;
  currentModel: string | null;
  deviceId: string;
  timestamp: string;
}

export async function gatherCrashReportData(
  error: Error,
  componentStack?: string,
  currentModel?: string | null
): Promise<CrashReportData> {
  // Get async values
  const [appVer, deviceId] = await Promise.all([
    getVersion().catch(() => 'Unknown'),
    invoke<string>('get_device_id').catch(() => 'Unknown'),
  ]);

  // Get sync values from OS plugin (these are not promises)
  let os = 'Unknown';
  let osVer = 'Unknown';
  let architecture = 'Unknown';

  try {
    os = platform();
    osVer = osVersion();
    architecture = arch();
  } catch (e) {
    console.error('Failed to get OS info:', e);
  }

  return {
    errorMessage: error.message || 'Unknown error',
    errorStack: error.stack,
    componentStack: componentStack,
    appVersion: appVer,
    platform: os,
    osVersion: osVer,
    architecture,
    currentModel: currentModel || null,
    deviceId,
    timestamp: new Date().toISOString(),
  };
}

export function generateGitHubIssueUrl(data: CrashReportData): string {
  const repo = 'moinulmoin/voicetypr';
  const title = `[Crash Report] ${truncate(data.errorMessage, 80)}`;

  const body = `## Crash Report

**Error Message:**
\`\`\`
${data.errorMessage}
\`\`\`

**Stack Trace:**
\`\`\`
${truncate(data.errorStack || 'No stack trace available', 2000)}
\`\`\`

${data.componentStack ? `**Component Stack:**
\`\`\`
${truncate(data.componentStack, 1000)}
\`\`\`

` : ''}## Environment

| Property | Value |
|----------|-------|
| App Version | ${data.appVersion} |
| Platform | ${data.platform} |
| OS Version | ${data.osVersion} |
| Architecture | ${data.architecture} |
| Current Model | ${data.currentModel || 'None'} |
| Timestamp | ${data.timestamp} |

## Additional Context

<!-- Please add any additional context about the crash here -->
- What were you doing when the crash occurred?
- Can you reproduce this crash?
- Any other relevant information?

---
*This report was auto-generated by VoiceTypr crash reporter*
`;

  const params = new URLSearchParams({
    title,
    body,
    labels: 'bug,crash-report',
  });

  return `https://github.com/${repo}/issues/new?${params.toString()}`;
}

function truncate(str: string, maxLength: number): string {
  if (str.length <= maxLength) return str;
  return str.slice(0, maxLength - 3) + '...';
}


export interface ManualReportData {
  name?: string;
  email?: string;
  message: string;
  appVersion: string;
  platform: string;
  osVersion: string;
  architecture: string;
  currentModel: string | null;
  deviceId: string;
  timestamp: string;
  logFileName: string | null;
  logContent: string;
  logTruncated: boolean;
  logStatusNote: string;
}

export interface LatestLogAttachment {
  file_name: string | null;
  redacted_content: string;
  original_byte_count: number;
  included_byte_count: number;
  truncated: boolean;
  status_note: string;
}

export async function gatherManualReportData(
  name: string | undefined,
  email: string | undefined,
  message: string,
  currentModel?: string | null
): Promise<ManualReportData> {
  const [appVer, deviceId, logAttachment] = await Promise.all([
    getVersion().catch(() => 'Unknown'),
    invoke<string>('get_device_id').catch(() => 'Unknown'),
    invoke<LatestLogAttachment>('get_latest_log_for_bug_report').catch(() => ({
      file_name: null,
      redacted_content: '',
      original_byte_count: 0,
      included_byte_count: 0,
      truncated: false,
      status_note: 'Failed to retrieve log.',
    } as LatestLogAttachment)),
  ]);

  let os = 'Unknown';
  let osVer = 'Unknown';
  let architecture = 'Unknown';

  try {
    os = platform();
    osVer = osVersion();
    architecture = arch();
  } catch (e) {
    console.error('Failed to get OS info:', e);
  }

  return {
    name,
    email,
    message,
    appVersion: appVer,
    platform: os,
    osVersion: osVer,
    architecture,
    currentModel: currentModel || null,
    deviceId,
    timestamp: new Date().toISOString(),
    logFileName: logAttachment.file_name,
    logContent: logAttachment.redacted_content,
    logTruncated: logAttachment.truncated,
    logStatusNote: logAttachment.status_note,
  };
}

interface BuildReportBodyOptions {
  includeLog?: boolean;
  omittedLogNote?: string;
}

export function buildReportBody(
  data: ManualReportData,
  options: BuildReportBodyOptions = {}
): string {
  const parts: string[] = [];

  parts.push('## VoiceTypr Support Report');
  parts.push('');

  if (data.name || data.email) {
    parts.push('### Contact');
    if (data.name) parts.push(`Name: ${data.name}`);
    if (data.email) parts.push(`Email: ${data.email}`);
    parts.push('');
  }

  parts.push('### Message');
  parts.push(data.message);
  parts.push('');

  parts.push('## Environment');
  parts.push('');
  parts.push('| Property | Value |');
  parts.push('|----------|-------|');
  parts.push(`| App Version | ${data.appVersion} |`);
  parts.push(`| Platform | ${data.platform} |`);
  parts.push(`| OS Version | ${data.osVersion} |`);
  parts.push(`| Architecture | ${data.architecture} |`);
  parts.push(`| Current Model | ${data.currentModel || 'None'} |`);
  parts.push(`| Timestamp | ${data.timestamp} |`);
  parts.push('');

  const includeLog = options.includeLog ?? true;

  // Latest log section
  if (includeLog && data.logContent) {
    parts.push('## Latest App Log');
    parts.push('');
    if (data.logTruncated) {
      parts.push('_The log was truncated. Only the most recent entries are included._');
    }
    if (data.logFileName) {
      parts.push(`_Source: ${data.logFileName}_`);
    }
    parts.push('');
    parts.push('```');
    parts.push(data.logContent);
    parts.push('```');
    parts.push('');
    parts.push('_Log content has been automatically redacted for common sensitive patterns._');
  } else if (!includeLog && options.omittedLogNote) {
    parts.push('## Latest App Log');
    parts.push('');
    parts.push(`> ${options.omittedLogNote}`);
  } else if (data.logStatusNote) {
    parts.push('');
    parts.push(`> ${data.logStatusNote}`);
  }

  parts.push('');
  parts.push('---');
  parts.push('_This report was generated by the VoiceTypr Report Bug feature._');

  return parts.join('\n');
}